### PR TITLE
fix: increases gas in BroadcastTx for umee e2e test to work in experimental mode

### PR DESCRIPTION
**Pull request by rbajollari**
## Description

closes: #XXXX

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] added appropriate labels to the PR
- [ ] targeted the correct branch
- [ ] provided a link to the relevant issue or specification
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items._

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by adamewozniak** [comment]
Might be a bit cleaner to just update the recommended config, wdyt?

**Comment by rbajollari** [comment]
> Might be a bit cleaner to just update the recommended config, wdyt?

Yeah I think that makes mores sense👍

**Comment by robert-zaremba** [comment]
weird... can't comment on a line of code.

Are we sure we need 1.5 here? Maybe 1.2 will be enough? Let's find a good value. Normally, PF txs should be for free, and attached fee should be 0.

If the gas adjustment is too high and total gas is too high then the PF will need to pay for the txs, which is against the design.

**Comment by rbajollari** [comment]
> weird... can't comment on a line of code.
> 
> Are we sure we need 1.5 here? Maybe 1.2 will be enough? Let's find a good value. Normally, PF txs should be for free, and attached fee should be 0.
> 
> If the gas adjustment is too high and total gas is too high then the PF will need to pay for the txs, which is against the design.

Tried different numbers and 1.03 is as low as I got it to work so I think thats the way to go

**Comment by adamewozniak** [comment]
> > weird... can't comment on a line of code.
> > Are we sure we need 1.5 here? Maybe 1.2 will be enough? Let's find a good value. Normally, PF txs should be for free, and attached fee should be 0.
> > If the gas adjustment is too high and total gas is too high then the PF will need to pay for the txs, which is against the design.
> 
> Tried different numbers and 1.03 is as low as I got it to work so I think thats the way to go

👍 if anything we can always recommend higher once umee comes out with cosmwasm

**Review by adamewozniak — APPROVED** [review]

**Pull request merged**
